version: '3'

services:
  app:
    build: ./
    image: sample
    env_file: ./app.env
    tty: true
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
    working_dir: "/app"
    command: npm run dev
    networks:
      - default
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    env_file: ./mysql/mysql.env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql
    networks:
      - default

networks:
  default:
volumes:
  mysqldata:
